"""Build the single served administration module from maintainable fragments."""

from argparse import ArgumentParser
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "frontend" / "admin"
OUTPUT = ROOT / "src" / "nvidia_build_lb" / "web" / "static" / "admin.js"
FRAGMENTS = (
    "01-schema.js",
    "02-state.js",
    "02-operation-result.js",
    "02-error-evidence.js",
    "02-stale-focus.js",
    "02-snapshot-expiry.js",
    "03-render-foundations.js",
    "03-render.js",
    "03-events.js",
    "03-local-intent.js",
    "03-decision-excluded.js",
    "03-decision.js",
    "04-reconciliation.js",
    "04-snapshot-coherence.js",
    "04-request.js",
    "04-network-auth.js",
    "04-network-load.js",
    "05-key-actions.js",
    "06-form-validation.js",
    "06-form-clipboard.js",
    "06-clipboard.js",
    "07-dialog-focus.js",
    "07-init.js",
)
HEADER = "/* Generated by scripts/build_admin_asset.py; edit frontend/admin/*.js. */"


def render_admin_asset() -> str:
    """Return deterministic one-resource JavaScript from ordered source fragments."""
    rendered = [HEADER]
    for name in FRAGMENTS:
        source = (SOURCE_ROOT / name).read_text(encoding="utf-8")
        compact = " ".join(line.strip() for line in source.splitlines() if line.strip())
        rendered.append(compact)
    return "\n".join(rendered) + "\n"


def main() -> int:
    """Write the asset or report whether the checked-in output is current."""
    parser = ArgumentParser()
    _ = parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_admin_asset()
    if args.check:
        return 0 if OUTPUT.read_text(encoding="utf-8") == rendered else 1
    OUTPUT.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
